services:
  accounts2:
    image: "mais85/accounts2:s4"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  loans2:
    image: "mais85/loans2:s4"
    container_name: loans-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  cards2:
    image: "mais85/cards2:s4"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"